name: Publish to PyPi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/vulcan-logger/
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v2
      name: Check out source code
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Replace '3.x' with the specific Python version you need, if necessary
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel # Install additional build dependencies if needed
    - name: Build and check the package
      run: |
        python setup.py sdist bdist_wheel
        twine check dist/*
    - name: Publish package distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/ # Use https://upload.pypi.org/legacy/ for PyPI
