name: Pylint
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: "*"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Specify the Python version you are using
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Pylint
        run: |
          # Run pylint and check only for errors. Other message types are ignored.
          pylint **/*.py --exit-zero --disable=C,R,W,I
